### ISSUE TITLE
`cargo build` requires `protobuf-compiler`

### ISSUE THREAD

**Issue by JMuff22** [BismuthCloud/faas#1]
Running `cargo build` requires `protoc` to be installed when building `bismuthd v0.1.0`. 

This issue can be resolved by adding instructions to the readme to install `protobuf-compiler` e.g `sudo apt-get install protobuf-compiler`. 

Issue discovered on ubuntu 22.04 LTS

**Comment by kallsyms** [comment]
Thanks for the note! Updated the readme with basic instructions for on-host development.
